### ISSUE TITLE
Compilation error with AppleClang 13

### ISSUE THREAD

**Issue by nilsleiffischer** [edouarda/brigand#274]
AppleClang 13 fails compiling tests with this error:

```
In file included from brigand/test/predicate_reduction_test.cpp:2:
In file included from brigand/include/brigand/algorithms/any.hpp:12:
brigand/include/brigand/algorithms/none.hpp:63:35: error: constexpr variable 'tester' must be initialized by a constant expression
        static constexpr all_same tester{static_cast<typename F<T>::type *>(nullptr),
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
brigand/include/brigand/algorithms/none.hpp:72:1: note: in instantiation of template class 'brigand::detail::none_impl<brigand::list<brigand::integral_constant<int, 0>, brigand::integral_constant<int, 0>, brigand::integral_constant<int, 0>, brigand::integral_constant<int, 0>, brigand::integral_constant<int, 0>, brigand::integral_constant<int, 0>>, brigand::detail::non_null_impl<brigand::_1>>' requested here
using none = typename detail::none_impl<Sequence, Predicate>::type;
^
brigand/test/predicate_reduction_test.cpp:10:24: note: in instantiation of template type alias 'none' requested here
static_assert(brigand::none<brigand::integral_list<int, 0, 0, 0, 0, 0, 0>>::value,
                       ^
brigand/include/brigand/algorithms/none.hpp:63:41: note: non-literal type 'std::initializer_list<integral_constant<bool, false> *>' cannot be used in a constant expression
        static constexpr all_same tester{static_cast<typename F<T>::type *>(nullptr),
                                        ^
```

**Comment by wthrowe** [comment]
Works on non-Apple clang 13.

Does it work if you add `constexpr` to `value` in `brigand/types/integral_constant.hpp`?  That is currently
```
    // no constexpr for maximum C++ 11 compatibility
    static const T value = Value;
```

I think it would fail before getting to that point if that is the problem, but we use this in SpECTRE with types that evaluate to STL constants (`is_same` types, technically) and that's one of the few differences.  (Pretty sure you told me compiling SpECTRE works with this setup.)
https://github.com/sxs-collaboration/spectre/blob/b8181c59f53c0d06029d9430ec12d720188ea8a3/src/Options/Options.hpp#L191-L192

The STL `integral_constant::value` was already constexpr in C++11, so I'm skeptical of there being any real compatability problems, despite the comment.

**Comment by jfalcou** [comment]
The comment probably dates from ild days of msvc. The fix looks easy enough, if someone with applz clang can confirm, I'll fix this

**Comment by wthrowe** [comment]
If you do end up changing that, marking `operator value_type()` and `operator()()` constexpr as well would be a nice convenience improvement.

**Comment by nilsleiffischer** [comment]
@wthrowe that doesn't immediately fix it

**Comment by wthrowe** [comment]
I've figured out how to reproduce this.  Here's a simple way to trigger the same problem:
```c++
#include <initializer_list>

template <typename T>
constexpr int g(std::initializer_list<T>) { return 0; }

void f() {
    constexpr int x = g({0});
}
```

It only happens with

* Clang 12+ (Apple version not required, 11 and below are fine)
* C++11 mode (14, 17 work)
* libc++

It seems likely to be relevant that in libc++ in C++11, `std::initializer_list` is not a literal type, but in libc++ C++14 or any libstdc++ it is.  So this might actually have been caused by *fixing* a bug in clang 12.

As to fixing it, I don't have an idea to make that method work, but there are `defined(BRIGAND_COMP_MSVC_2013) || defined(BRIGAND_COMP_CUDA) || defined(BRIGAND_COMP_INTEL)` implementations of `all` and `none` that doesn't use `std::initializer_list`, so switching to those if `defined(_LIBCPP_VERSION) && __cplusplus < 201402L` seems like an option.

Nothing else uses initializer lists in constexpr code, so these two should be the only problems.

@nilsleiffischer, can you try that out?  (I don't have easy access to Apple clang, and I've been cutting some corners in my testing so it is possible I screwed up.)  There's one `#if` near the top of each of `algorithms/all.hpp` and `algorithms/none.hpp` that need modifying.

**Comment by nilsleiffischer** [comment]
I can confirm that the alternative implementation in `all.hpp` and `none.hpp` fixes this issue with AppleClang. The issue is also fixed by selecting `CMAKE_CXX_STANDARD=14` or `17`.

Separate issue: C++14 and 17 trigger this static assert:

```
brigand/test/count_test.cpp:45:1: error: static_assert failed due to requirement 'brigand::integral_constant<unsigned long, 0>::value == 1' "eager count_if error"
static_assert(brigand::count_if<brigand::list<int>, brigand::bind<true_false, brigand::_1>>::value == 1, "eager count_if error");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by wthrowe** [comment]
Bug in a >=C++14 branch.  Nothing special with compilers or libraries.
```patch
diff --git a/include/brigand/algorithms/count.hpp b/include/brigand/algorithms/count.hpp
index 19382e6..e293665 100644
--- a/include/brigand/algorithms/count.hpp
+++ b/include/brigand/algorithms/count.hpp
@@ -108,7 +108,7 @@ namespace lazy
     struct count_if<S<Ts...>, bind<F, _1>>
     {
 #if __cplusplus >= 201402L
-        static constexpr std::array<bool, sizeof...(Ts)> s_v{{F<Ts>::type::value...}};
+        static constexpr std::array<bool, sizeof...(Ts)> s_v{{F<Ts>::value...}};
         using type = brigand::size_t<::brigand::detail::count_bools(s_v)>;
 #else
         static constexpr bool s_v[] = {F<Ts>::value...};
```
